api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cod-rules"
type = "function"
uid = "035060cc-35ef-c67c-df26-3d55cfa354811f1f5506"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
