-- AlterTable
ALTER TABLE "ShopSettings" ADD COLUMN     "dac7MinAmount" DECIMAL(12,2) NOT NULL DEFAULT 2000,
ADD COLUMN     "dac7MinTransactions" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "us1099kAmount" DECIMAL(12,2) NOT NULL DEFAULT 20000,
ADD COLUMN     "us1099kTransactions" INTEGER NOT NULL DEFAULT 200;

